services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hackathon-be
    ports:
      - "8080:8080"
    environment:
      APP_ENV: local
      APP_KEY: base64:MMwqwtFHEpcCMcU+4sBVYLzYlIqvyc4U2kRWx/Zuo8E=
      APP_DEBUG: "true"
      APP_URL: http://localhost:8080
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: laravel
      CACHE_STORE: database
      SESSION_DRIVER: database
      QUEUE_CONNECTION: database
    depends_on:
      db:
        condition: service_healthy
    command: sh ./docker/start.sh

  db:
    image: postgres:16-alpine
    container_name: hackathon-be-db
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: laravel
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U laravel -d laravel"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
