services:
  - type: web
    name: hackathon-be
    env: docker
    plan: free
    dockerCommand: ./docker/start.sh
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://hackathon-be.onrender.com
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: hackathon-be-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: hackathon-be-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: hackathon-be-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: hackathon-be-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: hackathon-be-db
          property: password
      - key: CACHE_STORE
        value: database
      - key: SESSION_DRIVER
        value: database
      - key: QUEUE_CONNECTION
        value: database

databases:
  - name: hackathon-be-db
    postgresMajorVersion: 16
    databaseName: hackathonbe
    user: hackathonbe
    plan: free
